### ISSUE TITLE
Lint against using `_super()` in a native class

### ISSUE THREAD

**Issue by pzuraq** [scalvert/eslint-plugin-ember-es6-class#3]
`_super` should never be used in native classes, and should be a lint error if it is called.

**Comment by rwjblue** [comment]
eslint-plugin-ember has [no-ember-super-in-es-classes](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-ember-super-in-es-classes.md), perhaps we can/should use that?

**Comment by pzuraq** [comment]
ah, yeah totally. Should we move it over here, or keep it over there? Probably makes sense to just keep it over there since this will be the default soon enough
